[tool.poetry]
name = "e2c"
version = "0.1.0"
description = "A command line tool to access English-to-Chinese database"
authors = ["zequnyu <zequnyu11@gmail.com>"]
license = "GPL-3.0"

[tool.poetry.scripts]
e2c = 'e2c:run_script.cli'
e2cs = 'e2c:run_script.search'

[tool.poetry.dependencies]
python = "^3.6.1"
loguru = "^0.5.1"
click = "^7.1.2"
colorama = "^0.4.3"
PyMuPDF = "^1.17.3"
numpy = "^1.19.0"
textblob = "^0.15.3"

[tool.poetry.dev-dependencies]
pre-commit = "^2.4.0"
flake8 = "^3.8.2"
black = "^19.10b0"
pytest = "^5.4.2"
pytest-cov = "^2.9.0"
pytest-xdist = "^1.32.0"
darglint = "^1.4.1"

[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
