name: CD

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v2
      with:
        python-version: "3.7"
    - uses: snok/install-poetry@v1.3.3
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Build wheels
      run: |
        poetry build
    - name: Upload wheel and tar ball
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: ./dist/*
  pypi:
    # Only run, if a tag is created on the default branch.
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') && github.repository == 'pastydev/cmdict'
    needs: build
    environment:
      name: pypi
      url: https://pypi.org/p/cmdict
    permissions:
      id-token: write
    runs-on: ubuntu-22.04
    steps:
      - name: Download wheel and tar ball built previously
        uses: actions/download-artifact@master
        with:
          name: dist
          path: ./dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
