name: CD

on:
  push:
    branches: [ master ]
    tags:
    - "**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - uses: snok/install-poetry@v1.3.3
      with:
        version: 1.5.1
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Build wheels
      run: |
        poetry build
    - name: Upload wheel and tar ball
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: ./dist/*
  pypi:
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') && github.repository == 'pastydev/cmdict'
    needs: build
    environment:
      name: pypi
      url: https://pypi.org/p/cmdict
    permissions:
      id-token: write
    runs-on: ubuntu-22.04
    steps:
      - name: Download wheel and tar ball built previously
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: ./dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
  version-patch:
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags') && github.repository == 'pastydev/cmdict'
    needs: pypi
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - uses: snok/install-poetry@v1.3.3
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Increase version by one patch
        run: |
          poetry version patch
      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: increase version by one patch after release [skip ci]
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: increase-version-${{ github.run_attempt }}
          delete-branch: true
          title: Increase version by one patch after release
          assignees: edxu96
          draft: false
          add-paths: pyproject.toml
          base: master
