name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - 'codecov.yml'
      - '.python-version'
      - 'poetry.toml'
  pull_request:
    types: [ opened, reopened ]
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - 'codecov.yml'
      - '.python-version'
      - 'poetry.toml'
  workflow_dispatch:

jobs:
  test:
    name: pre-commit and test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: [3.7.1, 3.6.7]
        os: [ubuntu-20.04, windows-2019, macos-11]

    steps:
    - uses: actions/checkout@master

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install -r ./requirements.txt

    - name: Check pre-commit
      run: pre-commit install && pre-commit run --all-files

    - name: Run pytest
      run: pytest -n auto --cov=./ --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
