name: CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/ci-poetry.yml'
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - 'codecov.yml'
      - '.python-version'
      - 'poetry.toml'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '.github/workflows/ci-poetry.yml'
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - 'codecov.yml'
      - '.python-version'
      - 'poetry.toml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: pre-commit and test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: [3.7, 3.8]
        # Need to fix the version of Ubuntu and macos, because Python
        # 3.6 is unavailable in x64 macos or arch x64 Ubuntu.
        # https://github.blog/2023-03-01-github-actions-introducing-faster-github-hosted-x64-macos-runners/.
        os: [ubuntu-20.04, windows-latest, macos-11]

    steps:
    - uses: actions/checkout@master

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Install dependencies
      run: |
        pip install -r ./requirements.txt

    - name: Check pre-commit
      run: pre-commit install && pre-commit run --all-files

    - name: Run pytest
      run: pytest -n auto --cov=./ --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1

  build:
    name: Build wheels
    runs-on: ubuntu-20.04
    needs: test
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@master

      - name: Install dependecies
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          cache: 'pip'

      - name: Build wheels
        run: |
          pip wheel -w ./dist/ .

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: ./dist/cmdict-*.whl
