# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: e2c

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-10.15

    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]
        poetry-version: [1.0.5]

    steps:
    - uses: actions/checkout@master
      
    - name: Install dependencies
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: ${{ matrix.python-version }}
        poetry_version: ${{ matrix.poetry-version }}
        args: install

    - name: Run pytest
      uses: abatilo/actions-poetry@v1.5.0
      with:
        python_version: ${{ matrix.python-version }}
        poetry_version: ${{ matrix.poetry-version }}
        args: run python -m pytest -n auto --cov=e2c
