name: cmdict

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: CI build
    runs-on: macos-latest

    strategy:
      matrix:
        python-version: [3.7]
        poetry-version: [1.0.5]

    steps:
    - uses: actions/checkout@master

    - name: Cache lfs database
      uses: actions/cache@v2
      with:
        path: .git/lfs
        key: .git/lfs

    - name: (IF NOT CACHED) Pull lfs database
      run: git lfs pull

    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install poetry
      uses: dschep/install-poetry-action@v1.3
      with:
        version: ${{ matrix.poetry-version }}

    - name: Install dependencies
      run: poetry install

    - name: Check pre-commit
      run: poetry run pre-commit install && poetry run pre-commit run --all-files

    - name: Run pytest
      run: poetry run pytest -n auto --cov=./ --cov-report=xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
