name: release

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - 'codecov.yml'
      - '.python-version'
      - 'poetry.toml'
  workflow_dispatch:

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/cmdict
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@master
      - name: Install dependecies, which will not be built again
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.1
          cache: 'pip'
      - name: Install poetry
        uses: snok/install-poetry@v1.3.3
      - name: Install dependencies
        run: |
          poetry install
      - name: Run test
        run: |
          poetry run pytest
      - name: Build wheels
        run: |
          poetry build
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
